// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_MessageBustsMZ","status":true,"description":"(v.1.2) Displays a bust image instead of selected face image","parameters":{"bPriority":"0","bPosition":"1","bX":"0","bY":"0","xOffset":"390","fileAppend":"","mStyleBusts":"false"}},
{"name":"GALV_LayerGraphicsMZ","status":true,"description":"(v.1.4) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.","parameters":{"fixPosition":"true"}}
];
